ARG VERSION=v3.13.2

FROM prom/prometheus:${VERSION}

# Copy the prom.yml configuration file to the container
COPY prom.yml /etc/prometheus/prom.yml
USER root
COPY entrypoint.sh /usr/local/bin/prometheus-entrypoint
RUN chmod 0555 /usr/local/bin/prometheus-entrypoint \
    && chown nobody:nobody /usr/local/bin/prometheus-entrypoint
USER nobody

# Command to run Prometheus
ENTRYPOINT ["/usr/local/bin/prometheus-entrypoint"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus", "--web.enable-remote-write-receiver"]
